### ISSUE TITLE
Task 1: Finmail Add-in Survey ($5-$10 or above for each approved report)

### ISSUE THREAD

**Issue by Masud115** [securechain/Finmail-Outlook#3]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Email for payment**
An email address with Finmail Add-in installed to receive payment

**Additional context**

**Comment by securechain** [comment]
The report does not address any issue, but just a copy of template. Therefore the report has no sufficient value and, will be closed without reward.
